name: My OT Spot
title: My OT Spot
description: my ot spot.
tags:
  - blog
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: /f/xdopleyw
disqus_username: lylace
